import FindMeetingPanel from './ui/FindMeetingPanel';
import FindMeetingFilters from './ui/FindMeetingFilterBtns';
import FindMeetingFilterCalendar from './ui/FindMeetingFilterCalendar';
import FindMeetingRegionSelector from './ui/FindMeetingRegionSelector';
import FindMeetingCardRow from './ui/FindMeetingCardRow';
import { MeetingCardInfo } from './model/types';

export default function FindMeetingView() {
  const info: MeetingCardInfo[] = [
    {
      meetingId: 1011,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: true,
      thumbnailUrl: '/assets/image/card-test-2.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1012,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: true,
      thumbnailUrl: '/assets/image/card-test-1.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1013,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: false,
      thumbnailUrl: '/assets/image/card-test-2.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1014,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: false,
      thumbnailUrl: '/assets/image/card-test-1.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1015,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: false,
      thumbnailUrl: '/assets/image/card-test-2.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1016,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: true,
      thumbnailUrl: '/assets/image/card-test-1.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1017,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: false,
      thumbnailUrl: '/assets/image/card-test-2.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1018,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: false,
      thumbnailUrl: '/assets/image/card-test-1.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1019,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: false,
      thumbnailUrl: '/assets/image/card-test-2.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1020,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: true,
      thumbnailUrl: '/assets/image/card-test-1.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1021,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: true,
      thumbnailUrl: '/assets/image/card-test-2.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1022,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: false,
      thumbnailUrl: '/assets/image/card-test-1.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1023,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: false,
      thumbnailUrl: '/assets/image/card-test-2.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1024,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: false,
      thumbnailUrl: '/assets/image/card-test-1.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1025,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: true,
      thumbnailUrl: '/assets/image/card-test-2.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1026,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: true,
      thumbnailUrl: '/assets/image/card-test-1.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1027,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: true,
      thumbnailUrl: '/assets/image/card-test-2.png',
      status: 'open',
      drinkType: 'whisky',
    },
    {
      meetingId: 1028,
      meetingAuthor: '홍길동',
      meetingTitle: '우리 오늘 취해봐요~ 낭만에 취해요',
      location: {
        sido: '경기도',
        address: '경기도 성남시 판교역로 123',
        detail: '102호',
      },
      participationFee: 20_000,
      startAt: new Date(),
      joinEndAt: new Date(),
      maxParticipants: 5,
      minParticipants: 3,
      currentParticipants: 2,
      isWished: true,
      thumbnailUrl: '/assets/image/card-test-1.png',
      status: 'open',
      drinkType: 'whisky',
    },
  ];

  return (
    <div className="w-[1000px] mx-auto px-0.5">
      <div className="flex mt-6">
        <FindMeetingPanel />
      </div>
      <div className="flex mt-8 py-4 border-b-1">
        <FindMeetingFilters />
      </div>
      <div className="flex mt-4">
        <FindMeetingRegionSelector />
        <FindMeetingFilterCalendar />
      </div>
      <div className="flex mt-6">
        <FindMeetingCardRow meetingCardList={info} />
      </div>
    </div>
  );
}
